apiVersion: v1
kind: ResourceQuota
metadata:
  name: max-running-jobs-in-namespace
  namespace: default
spec:
  hard:
    count/pods: "30"
  scopeSelector:
    matchExpressions:
      - scopeName: NotTerminating
        operator: Exists