spring:
  application:
    name: kubernetesjoblauncher

kubernetesjoblauncher:
  launcher:
    namespace: "default"
    # has to be higher than the time a pod needs to launch and claiming a message
    checksqsintervallms: "1000"
    jobtemplateconfigmapname: "job-template-cm"
    jobtemplateconfigmapkey: "job-template.yaml"
    jobname: "myjob"
  queue:
    # connect from host to localstack: http://localhost:4566
    # connect from pod to localstack: http://localstack:4566
    endpoint: "http://localhost:4566"
    accesskey: "test"
    secretkey: "test"
    region: "eu-central-1"
    # connect from host to localstack: http://localhost:4566/000000000000/inputqueue
    # connect from pod to localstack: http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/inputqueue
    inputqueueurl: "http://sqs.eu-central-1.localhost.localstack.cloud:4566/000000000000/inputqueue"
