{{- if .Values.internalJobtemplate.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: target-job-template-cm
data:
  job-template.yaml: |
    apiVersion: batch/v1
    kind: Job
    metadata:
      labels:
        app: target-job
    spec:
      backoffLimit: 0
      template:
        spec:
          restartPolicy: Never
          containers:
            - name: example
              image: busybox
              command: ["sh", "-c", "echo Hello && exit 0"]
{{- end }}